nameOverride: ""
fullnameOverride: ""

replicas: 1

containers:
  imageRegistry: gitlab.praktikum-services.ru:5050/std-027-58/momo-store/
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  #tag: ""
  name: momo-frontend
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
    - name: frontend
      containerPort: 80

vpa:
  resources:
    minAllowed:
      cpu: 1m
      memory: 60Mi
    maxAllowed:
      cpu: 1
      memory: 500Mi

service:
  type: ClusterIP
  port: 80

livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80

ingress:
  enabled: true
  className: "nginx"
  fqdn: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

clusterissuer:
  name: http01-clusterissuer
  acmeserver: https://acme-staging-v02.api.letsencrypt.org/directory
  # acmeserver: https://acme-v02.api.letsencrypt.org/directory
  email: someem@dfdf.com
  secretName: tls-lecert-diplom
