stages:
  - release

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

upload-helm:
  stage: release
  image: alpine/k8s:1.27.13
  script:
    - helm package --version $VERSION k8s-chart/
    - curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file momo-store-${VERSION}.tgz ${NEXUS_REPO_URL}/momo-store-${VERSION}.tgz
  only:
    changes:
      - k8s-chart/**/*
