nameOverride: ""
fullnameOverride: ""

replicas: 1

containers:
  imageRegistry: gitlab.praktikum-services.ru:5050/std-027-58/momo-store/
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  #tag: ""
  name: momo-backend
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
    - name: backend
      containerPort: 8081

vpa:
  resources:
    minAllowed:
      cpu: 1m
      memory: 60Mi
    maxAllowed:
      cpu: 1
      memory: 500Mi

service:
  type: ClusterIP
  port: 8081

livenessProbe:
  httpGet:
    path: /health
    port: 8081
readinessProbe:
  httpGet:
    path: /health
    port: 8081
