---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {

    listen 80 default_server;
    server_name _;

    location /momo-store/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(?:products|categories|orders|metrics|auth|whoami) {
        proxy_pass http://backend:8081;
    }
    }
