# Секрет, необходимый, чтобывзаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-docker-config-secret
data:
  .dockerconfigjson: >-
    
type: kubernetes.io/dockerconfigjson
