---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-cm
data:
  nginx.conf: |
    server {

      listen 80 default_server;
      server_name _;
  
      location /momo-store/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
      }
  
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }
  
      location ~ ^/(?:products|categories|orders|metrics|auth|whoami) {
        proxy_pass http://{{ .Release.Name }}-backend-svc:8081;
      }

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }