apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-dep
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 11
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-config-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.containers.imageRegistry }}{{ .Values.containers.name }}:{{ .Values.containers.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.containers.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.containers.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-cm