---
{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ing
  annotations:
   kubernetes.io/ingress.class: nginx
   cert-manager.io/cluster-issuer: http01-clusterissuer
spec:
  ingressClassName: "{{ .Values.ingress.className }}"
  tls:
    - hosts:
        - "{{ .Values.ingress.fqdn }}"
      secretName: tls-2048-bilgicloud
  rules:
    - host: "{{ .Values.ingress.fqdn }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend-svc
                port:
                  number: 80
{{- end }}