# Секрет, необходимый, чтобывзаимодействовать с Docker Registry в GitLab:
# ---
# kind: Secret
# apiVersion: v1
# metadata:
#   name: docker-config-secret
# data:
#   .dockerconfigjson: >-
#     ${KUBE_DOCKER_REGISTRY}
# type: kubernetes.io/dockerconfigjson

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsiYXV0aCI6ImJXRnBibDl3ZFd4c09saEdjRFV4Y0dKNVUwUnVMVk5MUTBoNFFXUk4ifX19
type: kubernetes.io/dockerconfigjson
